export const DESCRIPTION = `Delegates image-understanding tasks to local specialist vision models (BLIP for captioning, CLIP for zero-shot classification and general-purpose embedding, CLIPSeg for text-prompted segmentation, OWLv2 for open-vocabulary object detection, DINOv2 for pure visual-similarity embedding, ViTPose for human pose estimation) via the local model bridge. This is ONE tool with seven operations, not seven tools — pick exactly one operation per call and only supply the fields that operation needs. Every operation takes a local image file (\`image_path\`) — a missing, unreadable, or unsupported-format file fails with a clear "not found or unsupported format" error, not a garbled result.

operation "caption" — generates a single short natural-language description of what's in the image (e.g. "a dog running on a beach"), with no predefined labels. Use this for "what's in this image?" / "describe this picture" when you have no specific candidate answers in mind. Not detailed analysis, OCR, or answers to specific questions about the image.
- Same underlying model as the standalone \`ImageCaption\` tool — for a plain "what's in this image" request with no other need, prefer calling \`ImageCaption\` directly instead; use this operation only when you're already using (or expect to also need) one of this tool's OTHER operations on the same image.

operation "classify" — scores the image against a list of candidate labels YOU supply (\`labels\`), returning each label's probability (ranked, sums to 1 across the labels you gave — not a calibrated open-set probability, and not evidence about any label you didn't include). Use this when you already have specific candidate answers in mind, e.g. "is this a cat or a dog?", "which of these product categories does this photo belong to?". If you don't have predefined labels to check, use "caption" instead — "classify" cannot invent categories, only score the ones you give it.

operation "detect" — finds WHERE objects matching your query text(s) (\`queries\`) appear in the image, returning bounding boxes + scores for each match (multiple detections per query possible; a query that doesn't appear yields no detection for it, not a forced answer). Use this for "where is X" / "how many Xs are in this image" / "find all the Y". \`threshold\` (default 0.1) is a minimum-score cutoff — raise it to cut low-confidence noise, lower it to catch more borderline matches.
- detect vs classify: "classify" scores whether the WHOLE image matches each of your labels (one score per label, no location) — use it for "what kind of image is this overall". "detect" finds WHERE specific things are within the image (boxes, possibly several per query) — use it for "where/how many". Don't use "classify" when the real question is about location or count.

operation "segment" — text-prompted segmentation: given one text \`prompt\` describing a single thing to look for, returns whether it was found plus a derived bounding box (NOT a pixel mask), confidence, and the fraction of the image the match covers. Use this when you need a location for one specific described region/object and a box is enough (not multiple separate objects at once — for that, use "detect"). \`threshold\` (optional, default 0.5) has a known false-positive tendency on genuinely ABSENT objects — if the real question is "is X actually present, or not" (as opposed to "assuming X is present, where is it"), raise \`threshold\` to roughly 0.7 for a stricter read; the default is tuned for "find where X is" on the assumption X is likely present, not "confirm X exists".

operation "pose" — human pose estimation: returns per-person bounding boxes plus the 17 standard COCO keypoints (e.g. "L_Shoulder", "R_Knee") with pixel coordinates and per-keypoint confidence. \`boxes\` (optional, COCO \`[x, y, width, height]\` format, one array per person) lets you supply where each person already is if you know it (e.g. from a prior "detect" call with a "person" query); omitted, it runs on the whole image as a single box. Only useful when people are actually present — low confidence on non-photographic or people-free input is expected model behavior, not a bug, and should be reported honestly as low-confidence rather than treated as a real pose.

operation "embed" — CLIP embedding: a 768-dimensional, L2-normalized, general-purpose image embedding in a space that also aligns with CLIP's TEXT embeddings (so it supports cross-modal "does this image match this text" style similarity, and image-to-image similarity/search/dedup). Use this for building or querying an image-similarity/search index, or any case where you specifically need CLIP's space.

operation "embed-dinov2" — DINOv2 embedding: a 384-dimensional, L2-normalized, PURELY VISUAL embedding (no text alignment at all — it cannot be compared to a text query the way CLIP's can). Use this for pure visual-similarity tasks (near-duplicate detection, visual clustering) where you don't need any text-to-image comparison.
- CRITICAL: "embed" (CLIP) and "embed-dinov2" (DINOv2) vectors are NOT comparable to each other — different models, different dimensionality, different spaces. Never mix them in the same similarity computation (e.g. don't compute a cosine similarity between one image's CLIP embedding and another image's DINOv2 embedding). Pick one operation and use it consistently for a given comparison.

When NOT to use this tool:
- Detailed multi-part visual reasoning, OCR/reading text in an image, or answering an open-ended question about an image's content — none of these seven operations does open-ended visual question answering; they are narrow specialist tasks (caption / classify against given labels / locate / segment one region / estimate pose / embed).
- Non-image files, or a file path you don't actually have (this tool cannot invent an image to analyze).

Output: only the fields for the operation you called are present in the result; treat any other field as absent, not zero/false. For "segment", \`found: false\` (or a missing \`box\`) is a real, useful finding ("this was not found"), not a failure — report it as such, same as an empty \`speech_segments\` list from AudioAnalyze's "vad" operation is a real finding rather than an error.`

export const PROMPT = DESCRIPTION
